"""Tests for the dream management API."""
import base64
from collections.abc import Iterable
from datetime import datetime, timedelta
from http import HTTPStatus
from typing import TypeAlias

from fastapi.testclient import TestClient

from app.main import create_app
from app.services.narrative import NarrativeResult
from app.services.transcription import TranscriptionResult

Payload: TypeAlias = dict[str, object | None]

EXPECTED_TRANSCRIPTION_CONFIDENCE = 0.75
EXPECTED_MULTI_DREAM_TOTAL = 2


class _StubNarrativeEngine:
    def __init__(self) -> None:
        self.calls: list[dict[str, object]] = []

    def journal(
        self,
        *,
        title: str,
        transcript: str,
        mood: str | None,
        focus_points: Iterable[str],
        tone: str | None,
    ) -> NarrativeResult:
        self.calls.append(
            {
                "title": title,
                "transcript": transcript,
                "mood": mood,
                "focus": list(focus_points),
                "tone": tone,
            }
        )
        return NarrativeResult(narrative=f"{title} :: {transcript[:40]}", engine="stub")


class _StubTranscriptionEngine:
    def __init__(self) -> None:
        self.calls: list[dict[str, object]] = []

    def transcribe(self, *, audio: bytes, prompt: str | None) -> TranscriptionResult:
        self.calls.append({"audio": audio, "prompt": prompt})
        return TranscriptionResult(
            transcript=audio.decode("utf-8"),
            engine="stub",
            confidence=EXPECTED_TRANSCRIPTION_CONFIDENCE,
        )


def _create_client() -> TestClient:
    app = create_app()
    app.state.narrative_engine = _StubNarrativeEngine()
    app.state.transcription_engine = _StubTranscriptionEngine()
    return TestClient(app)


def test_create_and_retrieve_dream() -> None:
    client = _create_client()

    payload: Payload = {
        "title": "Flying above mountains",
        "transcript": "I was gliding over snowy peaks with a warm sunrise in the distance.",
        "tags": ["flight", "mountain"],
        "mood": "calm",
    }

    response = client.post("/dreams/", json=payload)
    assert response.status_code == HTTPStatus.CREATED
    created = response.json()
    assert created["id"] == "1"
    assert created["summary"].startswith("I was gliding")
    assert "mountain" in created["tags"]
    assert created["journal"] is None

    list_response = client.get("/dreams/")
    assert list_response.status_code == HTTPStatus.OK
    data = list_response.json()
    dreams = data["dreams"]
    assert data["total"] == 1
    assert len(dreams) == 1
    assert dreams[0]["id"] == "1"

    detail_response = client.get("/dreams/1")
    assert detail_response.status_code == HTTPStatus.OK
    detail = detail_response.json()
    assert detail["transcript"] == payload["transcript"]


def test_autogenerated_tags_and_highlights() -> None:
    client = _create_client()

    payload: Payload = {
        "title": "Chasing colours",
        "transcript": (
            "Colours spiralled around a crystal forest with luminous wolves running beside me."
        ),
        "tags": [],
        "mood": None,
    }

    response = client.post("/dreams/", json=payload)
    assert response.status_code == HTTPStatus.CREATED
    body = response.json()
    assert body["tags"], "Expected auto generated tags to be present"

    highlights = client.get("/dreams/highlights")
    assert highlights.status_code == HTTPStatus.OK
    summary = highlights.json()
    assert summary["total_count"] == 1
    first_tag = summary["top_tags"][0]["tag"]
    assert first_tag in body["tags"]
    assert summary["moods"] == []


def test_filtering_by_tag() -> None:
    client = _create_client()

    client.post(
        "/dreams/",
        json={
            "title": "Forest run",
            "transcript": "I ran through a forest with glowing foxes.",
            "tags": ["forest"],
            "mood": "energised",
        },
    )
    client.post(
        "/dreams/",
        json={
            "title": "Ocean dive",
            "transcript": "Swimming under bioluminescent waves with friends.",
            "tags": ["ocean", "friends"],
            "mood": "joyful",
        },
    )

    filtered = client.get("/dreams/", params={"tag": "forest", "limit": 5})
    assert filtered.status_code == HTTPStatus.OK
    filtered_body = filtered.json()
    assert filtered_body["total"] == 1
    assert len(filtered_body["dreams"]) == 1
    assert filtered_body["dreams"][0]["title"] == "Forest run"

    limited = client.get("/dreams/", params={"limit": 1})
    assert limited.status_code == HTTPStatus.OK
    limited_body = limited.json()
    assert limited_body["total"] == EXPECTED_MULTI_DREAM_TOTAL
    assert len(limited_body["dreams"]) == 1


def test_get_missing_dream_returns_404() -> None:
    client = _create_client()

    response = client.get("/dreams/999")
    assert response.status_code == HTTPStatus.NOT_FOUND
    body = response.json()
    assert body["detail"] == "Dream not found"


def test_update_dream_recalculates_summary_and_tags() -> None:
    client = _create_client()

    create_response = client.post(
        "/dreams/",
        json={
            "title": "Forest flight",
            "transcript": "I flew with owls between towering trees.",
            "tags": ["owls"],
            "mood": "excited",
        },
    )
    assert create_response.status_code == HTTPStatus.CREATED

    update_response = client.put(
        "/dreams/1",
        json={
            "transcript": "Exploring luminous caverns with glowing crystals and owls.",
            "mood": "curious",
        },
    )
    assert update_response.status_code == HTTPStatus.OK
    payload = update_response.json()
    assert payload["mood"] == "curious"
    assert payload["summary"].startswith("Exploring luminous caverns")
    assert "crystals" in payload["tags"], "Expected auto-tag merging with existing tags"
    assert "owls" in payload["tags"]


def test_updating_transcript_clears_existing_journal() -> None:
    client = _create_client()

    create_response = client.post(
        "/dreams/",
        json={
            "title": "Starlit dunes",
            "transcript": "I wandered across glowing sand while constellations pulsed overhead.",
            "tags": [],
            "mood": "reflective",
        },
    )
    assert create_response.status_code == HTTPStatus.CREATED

    journal_response = client.post(
        "/dreams/1/journal",
        json={"focus_points": ["constellations"], "tone": "soothing"},
    )
    assert journal_response.status_code == HTTPStatus.OK
    journal_payload = journal_response.json()
    dream_snapshot = journal_payload["dream"]
    assert dream_snapshot["journal"] is not None
    assert dream_snapshot["journal_generated_at"] is not None

    update_response = client.put(
        "/dreams/1",
        json={
            "transcript": "I drifted through a nebula with shimmering whales guiding the way.",
        },
    )
    assert update_response.status_code == HTTPStatus.OK
    updated = update_response.json()
    assert updated["journal"] is None
    assert updated["journal_generated_at"] is None


def test_update_missing_dream_returns_404() -> None:
    client = _create_client()

    response = client.put(
        "/dreams/404",
        json={"title": "Missing", "transcript": "No entry."},
    )
    assert response.status_code == HTTPStatus.NOT_FOUND
    assert response.json()["detail"] == "Dream not found"


def test_delete_dream_removes_entry() -> None:
    client = _create_client()

    client.post(
        "/dreams/",
        json={
            "title": "Ocean dive",
            "transcript": "Swimming with dolphins in clear water.",
            "tags": ["ocean"],
            "mood": "joyful",
        },
    )

    delete_response = client.delete("/dreams/1")
    assert delete_response.status_code == HTTPStatus.NO_CONTENT
    assert delete_response.content == b""

    get_response = client.get("/dreams/1")
    assert get_response.status_code == HTTPStatus.NOT_FOUND


def test_list_filters_by_query_and_date() -> None:
    client = _create_client()

    first = client.post(
        "/dreams/",
        json={
            "title": "Luminous cavern",
            "transcript": "Crystals hummed as I walked.",
            "tags": ["cavern"],
            "mood": "awed",
        },
    )
    assert first.status_code == HTTPStatus.CREATED
    second = client.post(
        "/dreams/",
        json={
            "title": "Ocean drift",
            "transcript": "I floated beside glowing dolphins.",
            "tags": ["ocean"],
            "mood": "calm",
        },
    )
    assert second.status_code == HTTPStatus.CREATED

    first_created = datetime.fromisoformat(first.json()["created_at"])
    query_response = client.get("/dreams/", params={"query": "dolphins"})
    assert query_response.status_code == HTTPStatus.OK
    payload = query_response.json()
    assert payload["total"] == 1
    assert payload["dreams"][0]["title"] == "Ocean drift"

    date_response = client.get(
        "/dreams/",
        params={"start": (first_created + timedelta(seconds=1)).isoformat()},
    )
    assert date_response.status_code == HTTPStatus.OK
    date_payload = date_response.json()
    assert date_payload["total"] == 1
    assert date_payload["dreams"][0]["title"] == "Ocean drift"


def test_generate_journal_updates_store() -> None:
    client = _create_client()

    create_response = client.post(
        "/dreams/",
        json={
            "title": "Forest echo",
            "transcript": "A stag guided me through misty trees.",
            "tags": ["forest"],
            "mood": "curious",
        },
    )
    assert create_response.status_code == HTTPStatus.CREATED

    response = client.post(
        "/dreams/1/journal",
        json={"focus_points": ["stag", "mist"], "tone": "hopeful"},
    )
    assert response.status_code == HTTPStatus.OK
    body = response.json()
    assert body["engine"] == "stub"
    assert "Forest echo" in body["narrative"]
    assert body["dream"]["journal"].startswith("Forest echo")
    assert body["dream"]["journal_generated_at"] is not None

    details = client.get("/dreams/1")
    assert details.status_code == HTTPStatus.OK
    detail_payload = details.json()
    assert detail_payload["journal"].startswith("Forest echo")


def test_transcribe_audio_endpoint() -> None:
    client = _create_client()

    sample = "Walking a spiral staircase"
    encoded = base64.b64encode(sample.encode()).decode()

    response = client.post(
        "/dreams/transcribe",
        json={"audio_base64": encoded, "prompt": "dream diary"},
    )
    assert response.status_code == HTTPStatus.OK
    body = response.json()
    assert body["transcript"] == sample
    assert body["engine"] == "stub"
    assert body["confidence"] == EXPECTED_TRANSCRIPTION_CONFIDENCE
