"""Pydantic schemas representing dream capture data."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime

from pydantic import BaseModel, Field, model_validator


class DreamBase(BaseModel):
    """Shared attributes between dream payloads."""

    title: str = Field(
        ..., max_length=120, description="Short label for the recorded dream"
    )
    transcript: str = Field(
        ...,
        min_length=1,
        description="Verbatim description captured from the user",
    )
    tags: list[str] = Field(default_factory=list, description="Keywords extracted from the dream")
    mood: str | None = Field(
        default=None,
        max_length=40,
        description="Optional mood descriptor chosen by the user after waking",
    )


class DreamCreate(DreamBase):
    """Payload received when a dream record is created."""

    pass


class DreamUpdate(BaseModel):
    """Payload accepted when mutating an existing dream entry."""

    title: str | None = Field(
        default=None,
        max_length=120,
        description="Updated title for the recorded dream",
    )
    transcript: str | None = Field(
        default=None,
        min_length=1,
        description="Revised transcript captured from the user",
    )
    tags: list[str] | None = Field(
        default=None,
        description="Explicit tags supplied by the user. Leave unset to auto-merge.",
    )
    mood: str | None = Field(
        default=None,
        max_length=40,
        description="Updated mood descriptor chosen by the user",
    )

    @model_validator(mode="after")
    def ensure_changes_present(self) -> DreamUpdate:
        """Guarantee that at least one attribute is supplied."""

        if all(
            getattr(self, field) is None
            for field in ("title", "transcript", "tags", "mood")
        ):
            raise ValueError("At least one field must be provided when updating a dream")
        return self


class Dream(DreamBase):
    """Representation of a stored dream."""

    id: str = Field(..., description="Stable identifier for the dream entry")
    summary: str = Field(..., description="Short AI generated summary of the dream")
    created_at: datetime = Field(..., description="Timestamp when the dream was recorded")
    journal: str | None = Field(
        default=None,
        description="Optional long-form journal generated by the AI",
    )
    journal_generated_at: datetime | None = Field(
        default=None,
        description="Timestamp when the journal was last generated",
    )


class DreamListResponse(BaseModel):
    """Envelope returned when multiple dreams are requested."""

    dreams: Sequence[Dream]
    total: int


class TagCount(BaseModel):
    """Keyword frequency pair used in highlight responses."""

    tag: str
    count: int


class MoodCount(BaseModel):
    """Mood frequency pair used in highlight responses."""

    mood: str
    count: int


class DreamHighlights(BaseModel):
    """Aggregated metrics derived from recorded dreams."""

    total_count: int
    top_tags: Sequence[TagCount] = Field(default_factory=list)
    moods: Sequence[MoodCount] = Field(default_factory=list)


class DreamJournalRequest(BaseModel):
    """Parameters accepted when generating a dream journal."""

    focus_points: list[str] = Field(
        default_factory=list,
        description="Specific symbols or motifs the user wants highlighted",
    )
    tone: str | None = Field(
        default=None,
        max_length=60,
        description="Optional tone such as 'hopeful', 'mysterious', or 'grounded'",
    )


class DreamJournalResponse(BaseModel):
    """Response envelope returned after generating a journal."""

    dream: Dream
    narrative: str
    engine: str


class DreamTranscriptionRequest(BaseModel):
    """Payload accepted when uploading audio for transcription."""

    audio_base64: str = Field(..., description="Base64 encoded audio sample")
    prompt: str | None = Field(
        default=None,
        description="Optional guiding phrases to improve transcription accuracy",
    )


class DreamTranscriptionResponse(BaseModel):
    """Transcription result returned to the caller."""

    transcript: str
    engine: str
    confidence: float
